null

diff --git a/poky/meta/recipes-graphics/wayland/weston-init/weston-start b/poky/meta/recipes-graphics/wayland/weston-init/weston-start
--- a/poky/meta/recipes-graphics/wayland/weston-init/weston-start
+++ b/poky/meta/recipes-graphics/wayland/weston-init/weston-start
@@ -6,7 +6,7 @@ export PATH="/sbin:/usr/sbin:/bin:/usr/bin"
 
 usage() {
 	cat <<EOF
-	$0 [<weston options>]
+	$0 [<openvt arguments>] [-- <weston options>]
 EOF
 }
 
@@ -18,12 +18,9 @@ add_weston_argument() {
 	weston_args="$weston_args $1"
 }
 
-## Add module to --modules argument
-add_weston_module() {
-	if [[ "x${weston_modules}" == "x" ]]; then
-		weston_modules="--modules "
-	fi;
-	weston_modules+="${1},"
+# Add openvt extra argument
+add_openvt_argument() {
+	openvt_args="$openvt_args $1"
 }
 
 if [ -n "$WAYLAND_DISPLAY" ]; then
@@ -32,11 +29,32 @@ if [ -n "$WAYLAND_DISPLAY" ]; then
 fi
 
 if [ -n "$WESTON_USER" ]; then
+	if [ -z "$WESTON_TTY" ]; then
+		echo "ERROR: If you have WESTON_USER variable set, you also need WESTON_TTY."
+		exit 1
+	fi
 	if [ -z "$WESTON_GROUP" ]; then
 		# no explicit WESTON_GROUP given, therefore use WESTON_USER
 		export WESTON_GROUP="${WESTON_USER}"
 	fi
+	weston_args_user="-u $WESTON_USER -t $WESTON_TTY"
 fi
+
+if [ -n "$DISPLAY" ]; then
+	launcher="weston"
+else
+	launcher="weston-launch $weston_args_user --"
+fi
+
+openvt_args="-s"
+while [ -n "$1" ]; do
+	if [ "$1" = "--" ]; then
+		shift
+		break
+	fi
+	openvt_args="$openvt_args $1"
+	shift
+done
 
 weston_args=$*
 
@@ -50,9 +68,6 @@ if [ -d "$modules_dir" ]; then
 
 		# process module
 		. $m
-		if [[ x"{$weston_modules}" != "x" ]]; then
-			add_weston_argument "${weston_modules}"
-		fi;
 	done
 fi
 
@@ -68,4 +83,4 @@ if test -z "$XDG_RUNTIME_DIR"; then
 	fi
 fi
 
-su -c "XDG_RUNTIME_DIR=/run/user/`id -u ${WESTON_USER}` weston $weston_args --log=/tmp/weston.log" $WESTON_USER
+exec openvt $openvt_args -- $launcher $weston_args --log=@LOCALSTATEDIR@/log/weston.log
diff --git a/poky/meta/recipes-support/lz4/files/run-ptest b/poky/meta/recipes-support/lz4/files/run-ptest
--- a/poky/meta/recipes-support/lz4/files/run-ptest
+++ b/poky/meta/recipes-support/lz4/files/run-ptest
@@ -1,17 +1,43 @@
 #!/bin/sh
+cd testsuite
 
-# Define test work dir
-WORKDIR=@PTEST_PATH@/tests/
+echo -n "---- test-lz4 ----"
+make -C tests test-lz4  > /dev/null 2>&1
 
-# Run test
-cd ${WORKDIR}
-
-case_name="test_frame"
-./frametest 
-ret=$?
-if [[ ${ret} == "0" ]]; then
-    echo "PASS: lz4/$case_name"
+if [ $? -eq 0 ]; then
+  echo "PASS"
 else
-    echo "FAIL: lz4/$case_name"
+  echo "FAIL"
 fi
 
+echo -n "---- test-fasttest ----"
+make -C tests test-fasttest  > /dev/null 2>&1
+if [ $? -eq 0 ]; then
+  echo "PASS"
+else
+  echo "FAIL"
+fi
+
+echo -n "---- test-frametest ----"
+make -C tests test-frametest > /dev/null 2>&1
+if [ $? -eq 0 ]; then
+  echo "PASS"
+else
+  echo "FAIL"
+fi
+
+echo -n "---- test-fullbench ----"
+make -C tests test-fullbench >  /dev/null 2>&1
+if [ $? -eq 0 ]; then
+  echo "PASS"
+else
+  echo "FAIL"
+fi
+
+echo -n "---- test-fuzzer ----"
+make -C tests test-fuzzer >  /dev/null 2>&1
+if [ $? -eq 0 ]; then
+  echo "PASS"
+else
+  echo "FAIL"
+fi
